private: false
name: INLG 2024
tagline: INLG 2024
date: September 23 - 27 2024
place: Tokyo, Japan
citation_date: September 2024
proceedings_title: Proceedings of the 17th International Natural Language Generation Conference
analytics: UA-
logo:
  image: static/images/inlg_logo.png
# uncomment the following line to show the site title next to the logo image
site_title:
page_title:
  prefix: "INLG 2024"
  separator: ": "
background_image: static/images/tokyo.jpg
organization: INLG 2024 Organizers

calendar:
  colors: #  Colors for the different event hashtags:
    ---: "#bed972"
    qa: "#4FCAEB"
    talk: "#ccc"
  sunday_saturday: false #  Include Sunday and Saturday
